### ISSUE TITLE
Infogans 

### ISSUE THREAD

**Issue by jethromoses** [Sachin-Wani/deeplearning.ai-GANs-Specialization#2]
Didn’t this course have some tutorial on infogans?

**Comment by Sachin-Wani** [comment]
Apparently not, I'm not sure if they have added it after the initial release. The files I have uploaded here contains the graded assignment files. So if infoGANs have been added, then it must be optional. You can always check the course content on Coursera.

**Comment by jethromoses** [comment]
It is optional. Do you not have access to it?

**Comment by Sachin-Wani** [comment]
Ok, I just saw it now. Yes, I have access to it. It's available in Course 1, Week 4. If you can't access it, just reset the deadlines and you will have the lab open with no problems

**Comment by jethromoses** [comment]
Unfortunately, I need to purchase a subscription to access it.

**Comment by Sachin-Wani** [comment]
See if you have joined the Slack forums or contact Coursera's Customer support. They might help you gain access to it

**Comment by jethromoses** [comment]
Alright, I'll do that. Thanks.

I thought it was an assignment similar to the ones you've uploaded.
